# fly.toml app configuration file generated for telebot-haxgad on 2026-02-16T12:09:19+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telebot-haxgad'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  auto_stop_machines = false
